# ViralCut Pro - Configuração para Render
# Deploy automático via GitHub

services:
  # Backend API Service
  - type: web
    name: viralcut-api
    runtime: node
    env: node
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # MySQL Hostinger Configuration
      - key: DB_HOST
        value: srv1883.hstgr.io
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: u206326127_viralcut
      - key: DB_USER
        value: u206326127_host
      - key: DB_PASS
        value: "@Host1603"
      - key: MONGODB_URI
        value: mysql://u206326127_host:@Host1603@srv1883.hstgr.io:3306/u206326127_viralcut
      # JWT Configuration
      - key: JWT_SECRET
        value: viralcut-pro-jwt-secret-2024-matheusbassini-render
      - key: JWT_REFRESH_SECRET
        value: viralcut-pro-refresh-secret-2024-matheusbassini-render
      - key: JWT_EXPIRE
        value: 15m
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      # Email Configuration - Hostinger SMTP
      - key: EMAIL_HOST
        value: smtp.hostinger.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: suporte@matheusbassini.com.br
      - key: EMAIL_PASS
        value: "@Suporte1603"
      - key: EMAIL_FROM
        value: suporte@matheusbassini.com.br
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_TLS
        value: true
      # Security Configuration
      - key: BCRYPT_ROUNDS
        value: 12
      - key: SESSION_SECRET
        value: viralcut-session-secret-2024-matheusbassini
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      # File Upload Configuration
      - key: MAX_FILE_SIZE
        value: 500MB
      - key: ALLOWED_FILE_TYPES
        value: video/mp4,video/avi,video/mov,video/mkv,video/webm
      # Application Configuration
      - key: TWO_FACTOR_SERVICE_NAME
        value: ViralCut Pro
      - key: LOG_LEVEL
        value: info
      # Frontend URL
      - key: FRONTEND_URL
        value: https://viralcut-frontend.onrender.com

  # Frontend Static Site
  - type: static
    name: viralcut-frontend
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
    routes:
      - type: rewrite
        source: /api/*
        destination: https://viralcut-api.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://viralcut-api.onrender.com/api
      - key: VITE_APP_NAME
        value: ViralCut Pro
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_DEVELOPER_NAME
        value: Matheus Bassini
      - key: VITE_DEVELOPER_EMAIL
        value: suporte@matheusbassini.com.br

# Configuração MySQL Hostinger
# IPs Outbound do Render que devem ser adicionados na Hostinger:
# - 44.229.227.142
# - 54.188.71.94  
# - 52.13.128.108
#
# Para adicionar os IPs:
# 1. Painel Hostinger → Databases → MySQL Databases
# 2. Encontrar: u206326127_viralcut → Manage
# 3. Remote MySQL → Add Host
# 4. Adicionar cada IP individualmente
#
# Credenciais MySQL:
# - Host: srv1883.hstgr.io
# - Port: 3306
# - Database: u206326127_viralcut
# - User: u206326127_host
# - Password: @Host1603
#
# Email SMTP Hostinger:
# - Host: smtp.hostinger.com
# - Port: 587
# - User: suporte@matheusbassini.com.br
# - Password: @Suporte1603
# - Webmail: https://mail.hostinger.com/
